name: Build, Test, and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install Dependencies
        run: npm install

      - name: Build application
        run: |
          echo "Building application..."

  snyk-scan:
    runs-on: ubuntu-latest
    needs: build  # This makes snyk-scan depend on the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  test:
    runs-on: ubuntu-latest
    needs: snyk-scan  # Ensure snyk-scan completes before running tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

  upload-artifact:
    runs-on: ubuntu-latest
    needs: test  # Ensures that tests have passed before uploading the artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Keep production dependencies
        run: |
          npm prune --production

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.sha_short }}
          path: |
            src/**/*
            !**/*.test.js
            node_modules
      
      - name: Trigger deployment in deployment repo # TODO
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: eros-assessment
          repo: devops
          github_token: ${{ secrets.ORG_TOKEN }}
          workflow_file_name: deploy-api.yml
          ref: dev
          wait_interval: 10
          # TODO envrionment
          client_payload: '{"tag":"${{ steps.vars.outputs.sha_short }}","artifact-id":"${{ steps.artifact.outputs.artifact-id }}", "workflow-run-id":"${{ github.run_id }}"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

  # trigger-deployment:
  #   runs-on: ubuntu-latest
  #   needs: upload-artifact
  #   steps:
      
    